### ISSUE TITLE
【请求头添加不成功】请求头header添加参数后，调取不成功

### ISSUE THREAD

**Issue by huangkunsds** [ChenSen5/api_autotest#1]
![image](https://user-images.githubusercontent.com/29912060/32765737-d91910a4-c946-11e7-958d-f3130cbfcf44.png)

**Comment by ChenSen5** [comment]
可以描述的更详细一点吗？如果时form-data的请求头时，请求post时，参数还是用json的形式传，代码会转换成form-data去请求的。如要传的参数是：user=abc&pass=123，对应json：{"user":"abc","pass":"123"}

**Comment by parkerqian** [comment]
我和一楼这个哥们碰到了同样的问题
在config.xml里面配置了 请求头的格式 为 form-data
<header name="Content-Type" value="form-data"></header>
我要测的这个接口是只支持form-data 格式的 不支持application/json
具体接口是这个https://www.juhe.cn/docs/api/id/11
我的XLS里面写的是这样的
https://user-images.githubusercontent.com/4987818/38778101-16893dda-40e6-11e8-9950-d04a0e8c6dc8.png


最后执行测试用例的时候报错了
{"resultcode":"101","reason":"错误的请求KEY!","result":null,"error_code":10001}

**Comment by wang1114yan** [comment]
> 我和一楼这个哥们碰到了同样的问题
> 在config.xml里面配置了 请求头的格式 为 form-data
> 
> 我要测的这个接口是只支持form-data 格式的 不支持application/json 具体接口是这个https://www.juhe.cn/docs/api/id/11 我的XLS里面写的是这样的 https://user-images.githubusercontent.com/4987818/38778101-16893dda-40e6-11e8-9950-d04a0e8c6dc8.png
> 最后执行测试用例的时候报错了
> {"resultcode":"101","reason":"错误的请求KEY!","result":null,"error_code":10001}

![image](https://user-images.githubusercontent.com/30361129/48308843-7d57b800-e5a7-11e8-9d03-ebcdffc4aa53.png)
把这个参数变为true就ok了

**Comment by ChenSen5** [comment]
使用form-data格式的时候，在配置中添加的请求头为
```
 <header name="content-type" value="multipart/form-data"></header>
```
用例填写的时候使用标准JSON进行设置，
如需要传参为：abc=123&def=456，那就在用例设置param为：
{"abc":"123","def":"456"}
如果没有生效的话把ApiTest.java文件中的源码：
```
private static boolean requestByFormData = false;
```
修改为
```
private static boolean requestByFormData = true;
```
