### ISSUE TITLE
Vim 下怎么跑项目？

### ISSUE THREAD

**Issue by wengyangjie** [ChenSen5/api_autotest#3]
![image](https://user-images.githubusercontent.com/31652405/69413400-b181bf00-0d4b-11ea-915b-7bf72d08ecb2.png)

**Comment by wengyangjie** [comment]
或者说不在javaIDE下怎么运行脚本？

**Comment by ChenSen5** [comment]
通过mvn命令启动：
```
mvn test
```

**Comment by wengyangjie** [comment]
> 通过mvn命令启动：
> 
> ```
> mvn test
> ```

![image](https://user-images.githubusercontent.com/31652405/69414073-fce89d00-0d4c-11ea-9d32-5c567bb18b2a.png)
这样是把baidu的demo 跑起来了么？

**Comment by wengyangjie** [comment]
![image](https://user-images.githubusercontent.com/31652405/69414226-42a56580-0d4d-11ea-9216-d168270fb3b4.png)
谢谢

**Comment by wengyangjie** [comment]
谢谢
