### ISSUE TITLE
无法校验json多层级的内容

### ISSUE THREAD

**Issue by wmlia** [ChenSen5/api_autotest#6]
{
    "code": 0,
    "data": {
        "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJzaG9wX2lkIjoxLCJleHAiOjE1NzU5ODQ0OTB9.FNNPajamJ9fNuDjZXn-nSRXhapbVQETEG04iX6az6ug",
        "first_login": false
    },
    "message": "成功"
}
$.first_login=false无法校验

**Comment by ChenSen5** [comment]
$.data.first_login=false

**Comment by wmlia** [comment]
原来是这样去校验，说明文档能说明一下会更好
