### ISSUE TITLE
请问URL不支持函数助手？还是我格式错误

### ISSUE THREAD

**Issue by wmlia** [ChenSen5/api_autotest#7]
1575535235332===url:http://www.doniwan.com/v2/api/app/shop/statistics/detail?type=2&page_num=1&debug=1&created_at=__date()
1575535235332===param:
1575535235358===返回状态码：200
1575535235358===resp:{"code":9000,"data":{"Func":"ParseInt","Num":"__date()","Err":{}},"message":"参数验证不正确"}
1575535235358===验证数据：$.code=0;$.message=成功;

url中__date()无法解析

**Comment by ChenSen5** [comment]
恩，还没支持，
你可以在preParam列重添加：xxxx=__date()
然后在url填写http://www.doniwan.com/v2/api/app/shop/statistics/detail?type=2&page_num=1&debug=1&created_at=${xxxx}
